"""initial schema

Revision ID: 001
Revises:
Create Date: 2026-08-11 16:18:20.499074

Hand-reviewed after autogenerate (UC2's convention -- autogenerate misses
some constructs on diffs, so the initial create is verified explicitly):
- both partial unique indexes rendered with their postgresql_where clauses
  (uq_extraction_jobs_active_document: status NOT IN terminal set;
  uq_identity_links_active_mention: WHERE active -- one live link/mention,
  append-only history preserved);
- all 29 named CHECK constraints from db/models.py's enum sets rendered
  inside their op.create_table calls;
- (element_type, value_normalized) ER blocking index and
  UNIQUE(person_id, category) / UNIQUE(sha256) present.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accuracy_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accuracy_runs'))
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_kind', sa.String(length=20), nullable=False),
    sa.Column('trigger', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('budget_max_steps', sa.Integer(), nullable=True),
    sa.Column('budget_max_tokens', sa.Integer(), nullable=True),
    sa.Column('budget_max_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('steps_used', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("agent_kind IN ('orchestrator', 'investigator', 'adjudicator', 'auditor')", name=op.f('ck_agent_runs_valid_agent_kind')),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'escalated', 'budget_exceeded', 'awaiting_approval', 'failed')", name=op.f('ck_agent_runs_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index('ix_agent_runs_agent_kind_status', 'agent_runs', ['agent_kind', 'status'], unique=False)
    op.create_table('manifest_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_uid', sa.String(length=100), nullable=False),
    sa.Column('rel_path', sa.String(length=1000), nullable=False),
    sa.Column('element_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('expected_locator', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manifest_elements'))
    )
    op.create_index('ix_manifest_elements_person_uid', 'manifest_elements', ['person_uid'], unique=False)
    op.create_index('ix_manifest_elements_rel_path', 'manifest_elements', ['rel_path'], unique=False)
    op.create_table('manifest_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_uid', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manifest_identities')),
    sa.UniqueConstraint('person_uid', name='uq_manifest_identities_person_uid')
    )
    op.create_table('processing_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('counters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('created', 'running', 'paused', 'finished', 'failed')", name=op.f('ck_processing_runs_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_runs'))
    )
    op.create_table('review_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('extraction', 'er_pair', 'flag_audit')", name=op.f('ck_review_items_valid_kind')),
    sa.CheckConstraint("status IN ('open', 'decided', 'dismissed')", name=op.f('ck_review_items_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_items'))
    )
    op.create_index('ix_review_items_kind_status', 'review_items', ['kind', 'status'], unique=False)
    op.create_table('accuracy_flag_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('accuracy_run_id', sa.UUID(), nullable=False),
    sa.Column('manifest_person_uid', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('expected', sa.Boolean(), nullable=False),
    sa.Column('predicted', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=5), nullable=False),
    sa.Column('error_class', sa.String(length=30), nullable=True),
    sa.CheckConstraint("category IN ('ssn', 'dob', 'drivers_license', 'passport', 'financial_account', 'credit_card', 'medical', 'credentials', 'address', 'phone', 'email')", name=op.f('ck_accuracy_flag_results_valid_category')),
    sa.CheckConstraint("error_class IS NULL OR error_class IN ('missed_extraction', 'ocr_failure', 'er_split', 'er_overmerge', 'trap_fp', 'wrong_category')", name=op.f('ck_accuracy_flag_results_valid_error_class')),
    sa.CheckConstraint("outcome IN ('tp', 'fp', 'fn', 'tn')", name=op.f('ck_accuracy_flag_results_valid_outcome')),
    sa.ForeignKeyConstraint(['accuracy_run_id'], ['accuracy_runs.id'], name=op.f('fk_accuracy_flag_results_accuracy_run_id_accuracy_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accuracy_flag_results'))
    )
    op.create_index('ix_accuracy_flag_results_accuracy_run_id', 'accuracy_flag_results', ['accuracy_run_id'], unique=False)
    op.create_table('accuracy_person_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('accuracy_run_id', sa.UUID(), nullable=False),
    sa.Column('manifest_person_uid', sa.String(length=100), nullable=False),
    sa.Column('matched_person_id', sa.UUID(), nullable=True),
    sa.Column('match_basis', sa.String(length=50), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.CheckConstraint("outcome IN ('matched', 'missed', 'split', 'wrongly_merged', 'hallucinated')", name=op.f('ck_accuracy_person_results_valid_outcome')),
    sa.ForeignKeyConstraint(['accuracy_run_id'], ['accuracy_runs.id'], name=op.f('fk_accuracy_person_results_accuracy_run_id_accuracy_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accuracy_person_results'))
    )
    op.create_index('ix_accuracy_person_results_accuracy_run_id', 'accuracy_person_results', ['accuracy_run_id'], unique=False)
    op.create_table('agent_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('request_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stop_reason', sa.String(length=30), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_agent_steps_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_steps')),
    sa.UniqueConstraint('agent_run_id', 'step_no', name='uq_agent_steps_agent_run_id')
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_type IN ('bulk_merge', 'final_signoff', 'class_pause')", name=op.f('ck_approval_requests_valid_action_type')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name=op.f('ck_approval_requests_valid_status')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_approval_requests_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index('ix_approval_requests_status', 'approval_requests', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('rel_path', sa.String(length=1000), nullable=False),
    sa.Column('declared_mime', sa.String(length=100), nullable=True),
    sa.Column('sniffed_mime', sa.String(length=100), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('file_class', sa.String(length=20), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('parent_document_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('is_image_based', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("file_class IN ('pdf_digital', 'pdf_scanned', 'docx', 'xlsx', 'csv', 'eml', 'msg', 'html', 'txt', 'png', 'unknown')", name=op.f('ck_documents_valid_file_class')),
    sa.CheckConstraint("source_kind IN ('corpus', 'attachment')", name=op.f('ck_documents_valid_source_kind')),
    sa.CheckConstraint("status IN ('queued', 'parsed', 'extracted', 'quarantined', 'failed', 'done')", name=op.f('ck_documents_valid_status')),
    sa.ForeignKeyConstraint(['parent_document_id'], ['documents.id'], name=op.f('fk_documents_parent_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.id'], name=op.f('fk_documents_run_id_processing_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('sha256', name='uq_documents_sha256')
    )
    op.create_index('ix_documents_run_id_status', 'documents', ['run_id', 'status'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('best_name', sa.String(length=300), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('er_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review_status IN ('auto', 'needs_review', 'human_confirmed')", name=op.f('ck_persons_valid_review_status')),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.id'], name=op.f('fk_persons_run_id_processing_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons'))
    )
    op.create_index('ix_persons_run_id', 'persons', ['run_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_item_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewer', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_items.id'], name=op.f('fk_review_decisions_review_item_id_review_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_decisions'))
    )
    op.create_index('ix_review_decisions_review_item_id', 'review_decisions', ['review_item_id'], unique=False)
    op.create_table('agent_tool_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_step_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=50), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_step_id'], ['agent_steps.id'], name=op.f('fk_agent_tool_calls_agent_step_id_agent_steps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_tool_calls'))
    )
    op.create_index('ix_agent_tool_calls_agent_step_id', 'agent_tool_calls', ['agent_step_id'], unique=False)
    op.create_table('cost_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("purpose IN ('tier1', 'tier2_text', 'tier2_vision', 'agent_orchestrator', 'agent_investigator', 'agent_adjudicator', 'agent_auditor', 'eval')", name=op.f('ck_cost_events_valid_purpose')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_cost_events_agent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_cost_events_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.id'], name=op.f('fk_cost_events_run_id_processing_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_events'))
    )
    op.create_index('ix_cost_events_run_id_purpose', 'cost_events', ['run_id', 'purpose'], unique=False)
    op.create_table('er_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('left_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('right_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('approval_request_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('merge', 'no_merge', 'split', 'escalate')", name=op.f('ck_er_decisions_valid_decision')),
    sa.CheckConstraint("method IN ('rule', 'agent', 'reviewer')", name=op.f('ck_er_decisions_valid_method')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_er_decisions_agent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], name=op.f('fk_er_decisions_approval_request_id_approval_requests'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_er_decisions'))
    )
    op.create_table('exposure_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('exposed', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('ssn', 'dob', 'drivers_license', 'passport', 'financial_account', 'credit_card', 'medical', 'credentials', 'address', 'phone', 'email')", name=op.f('ck_exposure_flags_valid_category')),
    sa.CheckConstraint("review_status IN ('auto', 'human_confirmed', 'human_overridden')", name=op.f('ck_exposure_flags_valid_review_status')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_exposure_flags_person_id_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exposure_flags')),
    sa.UniqueConstraint('person_id', 'category', name='uq_exposure_flags_person_id')
    )
    op.create_table('extraction_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tier_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_extraction_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_jobs'))
    )
    op.create_index('ix_extraction_jobs_status_created_at', 'extraction_jobs', ['status', 'created_at'], unique=False)
    op.create_index('uq_extraction_jobs_active_document', 'extraction_jobs', ['document_id'], unique=True, postgresql_where=sa.text("status NOT IN ('done', 'failed', 'quarantined')"))
    op.create_table('passages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ocr', sa.Boolean(), nullable=False),
    sa.Column('page_image_sha', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('page', 'sheet_range', 'email_part', 'text_block')", name=op.f('ck_passages_valid_kind')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_passages_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passages'))
    )
    op.create_index('ix_passages_document_id_seq', 'passages', ['document_id', 'seq'], unique=False)
    op.create_table('quarantines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('reason_code', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by_agent_run_id', sa.UUID(), nullable=True),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason_code IN ('password_protected', 'corrupt', 'zero_byte', 'wrong_extension', 'unsupported', 'ocr_garbage', 'parser_error')", name=op.f('ck_quarantines_valid_reason_code')),
    sa.CheckConstraint("stage IN ('ingest', 'parse', 'extract')", name=op.f('ck_quarantines_valid_stage')),
    sa.CheckConstraint("status IN ('open', 'agent_resolved', 'escalated', 'human_resolved')", name=op.f('ck_quarantines_valid_status')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_quarantines_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_agent_run_id'], ['agent_runs.id'], name=op.f('fk_quarantines_resolved_by_agent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quarantines'))
    )
    op.create_index('ix_quarantines_status', 'quarantines', ['status'], unique=False)
    op.create_table('mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('passage_id', sa.UUID(), nullable=False),
    sa.Column('name_raw', sa.String(length=300), nullable=False),
    sa.Column('name_normalized', sa.String(length=300), nullable=False),
    sa.Column('name_phonetic', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detector', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("detector IN ('llm_tier1', 'llm_tier2', 'deterministic_sheet')", name=op.f('ck_mentions_valid_detector')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_mentions_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], name=op.f('fk_mentions_passage_id_passages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentions'))
    )
    op.create_index('ix_mentions_document_id', 'mentions', ['document_id'], unique=False)
    op.create_index('ix_mentions_name_phonetic', 'mentions', ['name_phonetic'], unique=False)
    op.create_table('identity_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('mention_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('rule', 'agent', 'reviewer')", name=op.f('ck_identity_links_valid_method')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_identity_links_agent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], name=op.f('fk_identity_links_mention_id_mentions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_identity_links_person_id_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_links'))
    )
    op.create_index('ix_identity_links_person_id', 'identity_links', ['person_id'], unique=False)
    op.create_index('uq_identity_links_active_mention', 'identity_links', ['mention_id'], unique=True, postgresql_where=sa.text('active'))
    op.create_table('pii_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('passage_id', sa.UUID(), nullable=False),
    sa.Column('mention_id', sa.UUID(), nullable=True),
    sa.Column('element_type', sa.String(length=20), nullable=False),
    sa.Column('value_raw', sa.Text(), nullable=False),
    sa.Column('value_normalized', sa.String(length=500), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('context_snippet', sa.Text(), nullable=True),
    sa.Column('detector', sa.String(length=20), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("detector IN ('regex', 'checksum', 'llm_tier1', 'llm_tier2', 'reviewer')", name=op.f('ck_pii_elements_valid_detector')),
    sa.CheckConstraint("element_type IN ('ssn', 'ssn_last4', 'dob', 'drivers_license', 'passport', 'financial_account', 'credit_card', 'medical', 'credential', 'address', 'phone', 'email', 'name')", name=op.f('ck_pii_elements_valid_element_type')),
    sa.CheckConstraint("validation_status IN ('valid', 'invalid_checksum', 'format_only')", name=op.f('ck_pii_elements_valid_validation_status')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_pii_elements_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], name=op.f('fk_pii_elements_mention_id_mentions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], name=op.f('fk_pii_elements_passage_id_passages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pii_elements'))
    )
    op.create_index('ix_pii_elements_document_id', 'pii_elements', ['document_id'], unique=False)
    op.create_index('ix_pii_elements_element_type_value_normalized', 'pii_elements', ['element_type', 'value_normalized'], unique=False)
    op.create_table('flag_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exposure_flag_id', sa.UUID(), nullable=False),
    sa.Column('pii_element_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('passage_id', sa.UUID(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_flag_evidence_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exposure_flag_id'], ['exposure_flags.id'], name=op.f('fk_flag_evidence_exposure_flag_id_exposure_flags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], name=op.f('fk_flag_evidence_passage_id_passages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pii_element_id'], ['pii_elements.id'], name=op.f('fk_flag_evidence_pii_element_id_pii_elements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flag_evidence'))
    )
    op.create_index('ix_flag_evidence_exposure_flag_id', 'flag_evidence', ['exposure_flag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flag_evidence_exposure_flag_id', table_name='flag_evidence')
    op.drop_table('flag_evidence')
    op.drop_index('ix_pii_elements_element_type_value_normalized', table_name='pii_elements')
    op.drop_index('ix_pii_elements_document_id', table_name='pii_elements')
    op.drop_table('pii_elements')
    op.drop_index('uq_identity_links_active_mention', table_name='identity_links', postgresql_where=sa.text('active'))
    op.drop_index('ix_identity_links_person_id', table_name='identity_links')
    op.drop_table('identity_links')
    op.drop_index('ix_mentions_name_phonetic', table_name='mentions')
    op.drop_index('ix_mentions_document_id', table_name='mentions')
    op.drop_table('mentions')
    op.drop_index('ix_quarantines_status', table_name='quarantines')
    op.drop_table('quarantines')
    op.drop_index('ix_passages_document_id_seq', table_name='passages')
    op.drop_table('passages')
    op.drop_index('uq_extraction_jobs_active_document', table_name='extraction_jobs', postgresql_where=sa.text("status NOT IN ('done', 'failed', 'quarantined')"))
    op.drop_index('ix_extraction_jobs_status_created_at', table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    op.drop_table('exposure_flags')
    op.drop_table('er_decisions')
    op.drop_index('ix_cost_events_run_id_purpose', table_name='cost_events')
    op.drop_table('cost_events')
    op.drop_index('ix_agent_tool_calls_agent_step_id', table_name='agent_tool_calls')
    op.drop_table('agent_tool_calls')
    op.drop_index('ix_review_decisions_review_item_id', table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index('ix_persons_run_id', table_name='persons')
    op.drop_table('persons')
    op.drop_index('ix_documents_run_id_status', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_approval_requests_status', table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_table('agent_steps')
    op.drop_index('ix_accuracy_person_results_accuracy_run_id', table_name='accuracy_person_results')
    op.drop_table('accuracy_person_results')
    op.drop_index('ix_accuracy_flag_results_accuracy_run_id', table_name='accuracy_flag_results')
    op.drop_table('accuracy_flag_results')
    op.drop_index('ix_review_items_kind_status', table_name='review_items')
    op.drop_table('review_items')
    op.drop_table('processing_runs')
    op.drop_table('manifest_identities')
    op.drop_index('ix_manifest_elements_rel_path', table_name='manifest_elements')
    op.drop_index('ix_manifest_elements_person_uid', table_name='manifest_elements')
    op.drop_table('manifest_elements')
    op.drop_index('ix_agent_runs_agent_kind_status', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('accuracy_runs')
    # ### end Alembic commands ###
